import React from 'react';
import styled from 'styled-components';

const Margin = styled.div`
    margin-top: 10px;
`;

export default function Newsfeed() {
    return (
        <Margin>
             Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur luctus erat vitae purus molestie gravida. Phasellus vitae lectus ac nibh lacinia ullamcorper. Donec porta massa id purus cursus vulputate. Proin a leo ligula. Ut tristique blandit feugiat. Aliquam erat volutpat. Suspendisse vel justo massa. Nam eleifend lectus at metus imperdiet, efficitur dapibus purus sollicitudin.

Ut congue pulvinar lorem, placerat varius tortor molestie in. Nunc facilisis euismod urna, id porttitor arcu mollis tempus. Proin sit amet efficitur erat, sed interdum tellus. Donec vel lorem nibh. Ut vehicula quam vel quam sodales, in rutrum enim ultricies. Vestibulum congue ipsum at libero laoreet, non pulvinar lacus vehicula. Morbi viverra at diam sit amet consectetur. Sed eleifend ac nisi eu varius. Quisque eleifend elit non ipsum dignissim rhoncus. Fusce varius accumsan porttitor. Sed et sapien consectetur, rhoncus quam ut, pulvinar metus. Nam hendrerit lectus sit amet odio fringilla varius.

Nulla semper nisi maximus hendrerit malesuada. Ut quis feugiat dui, eu vestibulum metus. Duis lobortis, diam id gravida finibus, nunc turpis pulvinar nisl, ac egestas sem tellus vitae urna. Nam lectus magna, elementum non erat et, finibus pellentesque nunc. Aliquam erat volutpat. Suspendisse congue eget nunc mattis pharetra. Sed fringilla, sapien vel condimentum tempor, orci metus dapibus nulla, eget porttitor lorem augue nec quam. Fusce hendrerit, dolor id varius convallis, nulla lacus ullamcorper massa, sit amet porta enim erat a lectus. In scelerisque nibh nec bibendum consectetur. Maecenas pulvinar nunc orci, eget volutpat lacus ornare sed. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tincidunt eget nulla id cursus. Etiam diam enim, imperdiet in interdum vitae, sodales ac lacus. Morbi dictum dolor odio, porttitor dignissim ex laoreet sed. Mauris vitae ex quis justo tempus aliquet vel a elit.

Ut pretium enim nibh, eget blandit enim molestie vitae. In malesuada egestas ex, vitae lacinia ex rhoncus sit amet. Mauris ullamcorper lacus felis, ac imperdiet risus lobortis in. Proin non nisl non dolor pulvinar molestie lacinia ut sapien. Donec luctus non nisl sit amet blandit. Duis rutrum massa at vulputate volutpat. Vivamus dignissim malesuada metus, at convallis felis varius quis. Morbi fringilla aliquam diam nec sagittis.

Donec vitae diam a velit euismod sollicitudin a eget sapien. Fusce varius, orci sed tincidunt feugiat, risus metus malesuada quam, non rutrum urna ante id elit. Integer pellentesque metus ut sollicitudin pellentesque. In ornare dolor eget est blandit, vel vulputate metus porta. Phasellus lobortis convallis arcu. Duis tristique tempus nisi et viverra. Proin erat erat, vestibulum eget urna et, egestas euismod ante. Morbi in imperdiet lectus.

Phasellus accumsan velit non mollis tincidunt. Curabitur sit amet lacinia augue, imperdiet molestie neque. Mauris viverra enim id elit fermentum interdum. Donec at varius purus. Pellentesque nec vestibulum purus. Phasellus aliquam pellentesque elit sed euismod. In luctus pellentesque magna eget placerat. Donec elit arcu, mollis eu aliquet sit amet, pharetra vel metus. Nunc et luctus tellus. Donec fermentum imperdiet purus, vitae mollis mauris ultrices sed. Phasellus justo orci, placerat in lobortis at, congue eu metus.

Pellentesque sagittis quam ac ex facilisis vestibulum. Duis at tempus libero. Phasellus tincidunt pulvinar metus id malesuada. Pellentesque sodales tortor a diam eleifend vulputate. Sed pretium ornare lorem, at elementum sapien. Nullam viverra ultricies enim sit amet egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed pretium non dui at gravida. Ut auctor rhoncus justo a gravida. Donec eget vehicula augue. Vestibulum dignissim risus et nunc molestie, sit amet consectetur libero finibus.

Phasellus vel congue risus. Sed consequat accumsan lectus vitae tristique. Maecenas finibus diam a tempor mattis. In ornare pretium lacus at efficitur. Quisque non metus risus. Aliquam aliquet sapien tellus, aliquam hendrerit quam dapibus eget. Sed varius imperdiet tortor, ac pellentesque ante consectetur viverra.

Cras cursus urna a diam scelerisque gravida ac dictum eros. Phasellus est ante, sodales iaculis vehicula sed, lobortis id purus. Maecenas a risus ex. Duis vitae condimentum sem, at interdum massa. Vivamus risus diam, eleifend sed egestas vitae, commodo ac risus. Donec eleifend lacus eget pharetra cursus. Nam mattis enim id ante commodo pharetra. Aenean in justo enim. Sed consequat ultrices purus, id ornare elit. Phasellus ac nulla nisl.

In nec ligula vitae neque varius efficitur. Etiam vestibulum mattis orci, et suscipit dui efficitur quis. Maecenas efficitur pulvinar consequat. Proin elementum tortor augue, sit amet efficitur leo tempus sed. Proin vel porttitor elit. Sed tincidunt porttitor nunc non mattis. Morbi vulputate metus at sapien convallis interdum. Pellentesque erat velit, lobortis nec vulputate vitae, suscipit tempus diam. Nunc varius ac magna id fermentum. Maecenas non tortor pretium, egestas mauris eget, faucibus orci. Nulla nec ante et ligula mattis aliquam. Integer eu nisi vel urna congue ultricies a sodales augue. Sed sollicitudin sapien vitae commodo feugiat. Nam placerat congue viverra. Integer dui neque, tempor et malesuada et, cursus in tellus.

Donec vulputate, est venenatis mollis feugiat, ante ligula rhoncus velit, vitae interdum ligula purus sed lectus. Vestibulum et egestas magna, eu fermentum nibh. Integer placerat nulla condimentum mi viverra malesuada. Nunc iaculis ex in fermentum congue. Quisque leo purus, fermentum sed metus sit amet, pellentesque auctor diam. Curabitur et erat tincidunt, scelerisque orci a, tempor metus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed pretium, velit in faucibus finibus, diam sem porta nibh, eget eleifend ex tortor a lacus. Morbi sed ex sed metus dapibus pulvinar sed maximus magna. Vivamus pellentesque vitae quam at pulvinar. Cras nec iaculis tortor, vitae mattis sem.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris velit mauris, ornare at neque vel, accumsan viverra magna. Curabitur imperdiet, tellus sed ultrices sodales, felis lectus rhoncus libero, non efficitur ante risus a ex. Sed nec orci finibus elit ultrices dapibus. Sed sed porttitor justo. Phasellus turpis leo, tincidunt vel odio vitae, sollicitudin sagittis quam. Nullam est diam, scelerisque luctus rutrum eget, maximus vel purus. Curabitur ornare sem et nunc dignissim vulputate. Praesent sollicitudin euismod metus. Suspendisse viverra mi lacus, quis pretium massa iaculis at. Sed pretium odio posuere tortor facilisis interdum. Fusce dapibus eu ligula quis volutpat. Vivamus et felis sed sem pellentesque condimentum. Maecenas euismod metus at dui posuere consectetur. Mauris ornare lectus eget dui laoreet, in efficitur eros venenatis. Praesent vitae iaculis quam.

Cras aliquam est vel purus posuere, ut commodo ipsum aliquet. Phasellus feugiat lectus lobortis, vestibulum nunc et, gravida tellus. Etiam sed vehicula arcu. Proin lacinia nibh at orci placerat tincidunt. Duis in tellus blandit, fringilla eros quis, ullamcorper augue. Morbi eget auctor libero. Aliquam suscipit urna sed iaculis varius. Maecenas nec ornare lacus, quis tristique ligula. Phasellus at sagittis ipsum.

Cras id justo volutpat, eleifend felis vitae, mattis ex. Donec eu tristique urna. Fusce luctus consequat ornare. Suspendisse potenti. Suspendisse semper sit amet ante nec fermentum. Donec pharetra dolor vel neque pulvinar, sed accumsan libero fermentum. Vestibulum porta eget enim quis suscipit.

Vestibulum semper eu justo quis volutpat. In accumsan lectus non enim rhoncus, et consectetur turpis cursus. Praesent vel velit vel nulla semper iaculis. Fusce scelerisque consectetur elit, sed pellentesque purus feugiat vel. Proin nunc nisl, varius quis vehicula ac, vulputate eget ipsum. Sed vel enim sit amet ipsum accumsan porttitor at in ipsum. Nunc lacus arcu, pretium at fringilla et, vehicula ac risus. Aliquam neque risus, dignissim id vulputate ut, blandit vel sem. Etiam augue magna, vestibulum quis convallis vitae, tincidunt sit amet dolor. Nulla arcu purus, egestas non faucibus sit amet, rhoncus eu lorem. Vivamus pellentesque, lacus in commodo blandit, eros lacus varius nibh, ut eleifend purus diam vel metus. Vivamus efficitur augue imperdiet enim placerat laoreet. Nam libero enim, faucibus vel eleifend vitae, volutpat fermentum mi. Sed ut tellus orci. Aliquam erat volutpat.

Phasellus a rutrum nibh, ut pellentesque tortor. Donec congue nibh enim, non porta ipsum aliquam eget. Vivamus non nibh eu lorem suscipit semper. Aenean ac dapibus enim. Vestibulum egestas tortor eget ornare tincidunt. Suspendisse consectetur tellus at quam luctus placerat. Duis imperdiet nulla sed justo bibendum eleifend. Nullam eget dolor eget dui hendrerit blandit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In eget auctor lacus. Phasellus tempus lectus et scelerisque vehicula. Aliquam finibus ultricies blandit. Sed ac felis vel nisl condimentum pulvinar. Sed eget venenatis magna. Fusce lacinia ultricies varius.

Donec ut libero at nisl rutrum dictum. Praesent mollis sapien non leo sollicitudin convallis. Integer nibh nibh, volutpat ut lobortis nec, malesuada placerat metus. Nam in dignissim urna. Suspendisse ullamcorper nisl ac nisi tristique, ut fringilla sem luctus. Donec in arcu dui. Aliquam erat volutpat. Phasellus scelerisque tellus nec libero mollis feugiat.

Phasellus ultricies, sem vel imperdiet tincidunt, ligula velit mattis mauris, non aliquam dolor arcu vitae odio. Phasellus nec scelerisque sem. Vestibulum sit amet fermentum felis. Donec at lectus a erat posuere fringilla. Praesent eget consequat orci. Donec pharetra, mauris volutpat dignissim gravida, massa ante viverra leo, sed aliquam dui dolor ac dolor. Proin et orci mi. Quisque pretium scelerisque ornare. Mauris maximus eleifend quam vel mollis. Etiam malesuada justo et tincidunt tristique. Vivamus et turpis in dui consectetur consequat. Cras pharetra est in neque dapibus bibendum. Vestibulum pulvinar risus vel gravida fringilla. Donec tempus, justo quis posuere mattis, leo ligula consequat quam, in bibendum urna metus et justo. Duis iaculis erat ex, quis efficitur purus mollis sit amet.

Etiam imperdiet eu urna quis ultrices. Nam ut ultrices tortor, id imperdiet nulla. Suspendisse ornare, leo et consequat auctor, mauris justo volutpat erat, vitae placerat urna nisl facilisis magna. Etiam et aliquam enim, sed volutpat elit. Nullam semper pretium elit, ac rhoncus erat semper ac. Sed suscipit arcu libero. Aliquam erat volutpat. Etiam sit amet sem justo. Duis molestie suscipit odio quis ornare.

Praesent auctor orci sapien, eleifend auctor elit maximus nec. Aliquam consequat ex eu ultrices ultricies. Aenean aliquet efficitur ultricies. In rutrum urna at viverra semper. Cras vel tristique purus. Quisque nec orci vitae velit tincidunt feugiat. Duis sit amet diam in lorem condimentum ultrices. Ut ac leo ut quam tincidunt fermentum. Vestibulum elementum congue pretium. Mauris ut lorem a purus lobortis hendrerit fringilla vel mauris. Nulla consectetur ornare nisl, non condimentum sapien condimentum non. Mauris condimentum leo at ante dignissim, ut blandit magna aliquam. Ut aliquam dignissim ipsum posuere scelerisque.

Pellentesque nec tellus quam. In consectetur vulputate mi, et auctor lorem facilisis malesuada. Nunc eu ex eget lacus dignissim fringilla. Nullam a accumsan turpis. Maecenas imperdiet efficitur tellus, non porta nulla pulvinar eu. Suspendisse vel dui nisi. Mauris condimentum, lorem nec elementum sollicitudin, ante nulla dignissim odio, nec mollis ligula ex at libero. In massa ligula, pharetra in quam in, dictum viverra massa. Ut aliquam, turpis ac tempus sagittis, leo tortor ullamcorper purus, sit amet maximus sem sapien eu nisl. Integer a ligula consequat, rhoncus sapien at, aliquam eros. Integer aliquam tellus id tempus venenatis. In quis pulvinar libero, sit amet faucibus lorem.

Nunc vitae sollicitudin nisi, id pulvinar urna. Nunc porta aliquet mollis. Pellentesque bibendum et diam eu mollis. In quis porttitor sapien. Aenean hendrerit, nulla et porta fringilla, quam tellus suscipit quam, gravida tempus elit est non leo. Ut quis feugiat metus. Phasellus fermentum bibendum est ut vestibulum. Maecenas in libero finibus, venenatis eros quis, vestibulum nulla. Nam quis pulvinar sapien. Nullam eu auctor erat. Pellentesque mollis ante eu rutrum pharetra. Duis quis tempus augue. Nam convallis arcu vel porta pellentesque. Donec convallis dolor ut ex sagittis, vel feugiat neque ultrices. Maecenas sodales, mauris ut posuere vehicula, ligula ligula imperdiet arcu, non interdum tortor nulla ut eros.

Mauris id fermentum nisi, in accumsan ante. Ut a facilisis velit. Nam et enim ac est sagittis cursus. Proin consectetur dui quis neque blandit, et facilisis ipsum vehicula. Nunc vel scelerisque nisl, id tincidunt nunc. Nulla semper dignissim mattis. Sed ultrices cursus ante, sit amet accumsan turpis porta et. Aenean nec bibendum ante, at dictum dui. Duis elit justo, pharetra eget urna a, egestas malesuada odio. In nec odio luctus lacus pretium cursus. Nam eu urna a tortor bibendum suscipit. Proin sapien turpis, ullamcorper ac diam eget, tincidunt laoreet libero. Duis ipsum massa, auctor in blandit quis, pellentesque convallis est. Nam euismod suscipit nisi, eget vulputate orci maximus non. Etiam mollis venenatis bibendum.

Pellentesque tempor lacinia lorem sed facilisis. Nullam et aliquet nunc. Ut porttitor pellentesque eros. Suspendisse mi nunc, suscipit maximus dictum vel, euismod non ante. Curabitur justo lectus, porttitor at fermentum lobortis, fringilla ac lorem. Praesent ullamcorper nibh augue, non pulvinar ante dictum non. Duis posuere, leo at maximus egestas, felis neque egestas dui, vitae venenatis nibh felis eget quam. Pellentesque et odio a neque pulvinar tincidunt non vel mi. Pellentesque viverra varius dolor, in scelerisque augue aliquam et. Nulla dui turpis, auctor eu est vel, cursus finibus odio. Pellentesque ut egestas nisl, molestie interdum quam.

Sed at lorem laoreet, mollis velit ut, ornare turpis. Proin mi justo, ultricies id nibh sit amet, feugiat tincidunt mi. Vivamus a pharetra neque, sed tristique nulla. In luctus nisi neque, eu placerat turpis finibus egestas. Aenean malesuada tortor vel nibh euismod accumsan. Vestibulum fringilla, orci a pellentesque lacinia, ipsum elit accumsan dolor, sit amet congue nisl urna sit amet justo. Nam consectetur pretium consectetur.

Nam condimentum ligula vel ultricies tempor. Nulla urna turpis, congue eget eleifend semper, convallis vitae urna. Curabitur nisl est, mollis eu consequat iaculis, aliquam vel purus. Pellentesque justo turpis, pellentesque a pharetra sit amet, fermentum eget magna. Donec tempor urna eu dui sodales imperdiet. Aliquam cursus accumsan laoreet. Aliquam finibus et ex eget pellentesque. Cras tincidunt venenatis nibh vitae lacinia. Vivamus lacinia nunc id purus laoreet tincidunt. Praesent eu erat bibendum justo fringilla dictum. Morbi a pretium enim, sit amet sodales est. Aenean nec odio vel augue condimentum volutpat vitae in metus.

Integer auctor justo non pellentesque egestas. Proin et condimentum erat. Pellentesque mauris erat, accumsan eget nunc et, iaculis porttitor ipsum. Etiam quis justo venenatis, vulputate lacus at, pretium nibh. Vivamus ut nunc orci. In hac habitasse platea dictumst. Duis porta nisl in elit aliquam, ut tempus ipsum viverra. Nullam pharetra auctor dui, et luctus leo mattis quis. Curabitur aliquam nibh nunc, sed lobortis nisi luctus in. Phasellus mauris eros, auctor sit amet tristique non, facilisis sollicitudin lectus. Praesent varius egestas velit. Praesent ac interdum augue, sit amet lacinia felis.

Nunc molestie, urna in sollicitudin pretium, mi elit tincidunt dui, non tristique metus neque ut justo. Suspendisse tempus dapibus turpis eget convallis. Quisque feugiat sollicitudin ante sit amet aliquet. Suspendisse vel efficitur nibh. Duis a tempus eros. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc ornare elit et erat malesuada, at iaculis orci pharetra. Donec feugiat pellentesque enim, vel blandit nisi tristique quis. Nam vel lorem maximus, faucibus mauris id, placerat sapien.

Maecenas mattis dui in dignissim tristique. Vestibulum eget ipsum nec mi elementum lacinia. Vestibulum sed orci vel elit ullamcorper elementum. Vestibulum cursus sed tellus a interdum. Morbi maximus euismod ex sit amet rhoncus. Nullam semper a dui tincidunt pellentesque. Fusce nunc elit, condimentum quis orci non, rhoncus maximus ligula. Aliquam egestas euismod tortor a euismod. Duis neque lacus, blandit id arcu nec, pulvinar facilisis diam. In hac habitasse platea dictumst. Ut dignissim facilisis metus, in porta ante dapibus sit amet. Nunc ac orci ut dui porttitor volutpat. Morbi eu varius nisl. Aenean eget iaculis purus. Duis a odio congue, scelerisque magna quis, dictum libero.

Curabitur fermentum nisi enim, ut porttitor massa tempus sit amet. Pellentesque aliquet fringilla urna, et elementum libero euismod eu. Proin quis malesuada quam. Duis mi sapien, vulputate vitae dapibus ut, porta quis neque. Maecenas a tincidunt arcu. Nam in mi condimentum, iaculis magna id, lacinia lacus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut dictum quam non augue rhoncus venenatis. Nullam rhoncus finibus auctor. Maecenas pulvinar arcu non ex tincidunt rhoncus. Integer a enim felis. Duis eu lobortis ligula.

Aliquam eget lectus dolor. Proin mattis, libero eu elementum tincidunt, elit justo aliquet felis, elementum pharetra neque lorem quis leo. Sed dignissim lobortis metus sit amet varius. Pellentesque scelerisque accumsan facilisis. Phasellus fringilla erat ac dapibus viverra. Suspendisse accumsan lacus eget enim posuere, in semper dolor egestas. Nullam lacinia mauris in arcu facilisis, ac eleifend velit maximus. Mauris suscipit velit vitae facilisis imperdiet. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam a lacus dolor. Donec elit dui, malesuada vitae est ut, commodo pulvinar erat. Pellentesque aliquam sagittis sem, in varius nibh sodales et. Donec varius leo vitae odio lobortis condimentum.

Morbi pellentesque nisi vel sapien cursus, sed eleifend leo dapibus. Vestibulum eu dui convallis arcu semper cursus. Pellentesque pharetra, tellus in varius mattis, sem est commodo dolor, non bibendum orci dolor eu urna. Duis dictum nulla ut porttitor commodo. Pellentesque eget eros fringilla, scelerisque velit non, condimentum felis. Suspendisse tristique ipsum leo, sed tempor sem dictum vitae. Phasellus id suscipit purus. Cras non dui pretium, ultrices lectus id, pulvinar mi. Morbi rutrum ipsum quis facilisis malesuada. Phasellus lacinia faucibus felis pulvinar tincidunt. Suspendisse luctus mi ac tristique vehicula. Donec maximus velit vel mollis tempus.

In pellentesque mauris felis, eleifend bibendum ligula porttitor id. Quisque eleifend orci semper risus suscipit rhoncus. Vestibulum auctor ex eget volutpat vehicula. In tincidunt nisl risus, ac tristique dui laoreet eu. Nulla cursus augue eros, vitae rhoncus turpis feugiat nec. Sed suscipit sapien vel purus sollicitudin ullamcorper. Vivamus bibendum laoreet ex eu lobortis. Nullam pretium tellus eu justo malesuada, vitae dictum nulla efficitur. Nulla leo mauris, finibus vitae vestibulum at, bibendum nec nibh. Morbi commodo interdum nunc, eget tristique nisi viverra et. Fusce eleifend fringilla ligula, vitae egestas augue tristique quis. Cras et turpis orci. Ut at condimentum justo. Cras fringilla eros arcu, ut laoreet magna vestibulum ac. Etiam pulvinar metus pretium, mollis enim id, ultricies est. Etiam in volutpat dolor.

Suspendisse vel massa sed ipsum feugiat condimentum. Sed sit amet neque eu metus varius faucibus. Nunc ut venenatis orci. Vivamus suscipit magna ut massa fermentum, in lacinia est congue. In varius euismod lectus, tristique sollicitudin lorem blandit tempor. Phasellus libero lectus, efficitur ut ultrices id, sodales et dui. Phasellus molestie velit at egestas interdum.

Nulla facilisi. Donec nec rutrum ipsum. Nulla facilisi. Curabitur efficitur turpis sit amet lectus placerat, ac fermentum urna iaculis. Phasellus iaculis dui ipsum, vitae accumsan justo egestas nec. Praesent tellus ligula, commodo eu velit eu, tempus sagittis est. Integer convallis placerat tempus. Fusce arcu purus, rutrum quis tempor nec, tristique ut arcu.

Vestibulum vitae urna accumsan lacus suscipit pulvinar. Ut et mattis turpis. Nulla pulvinar felis ac purus dignissim, quis hendrerit dui laoreet. Nulla sagittis, dolor nec consequat mollis, magna turpis dictum ante, eget euismod leo orci vel augue. Aenean bland
        </Margin>
    )
}
